# Show a thin line around the windows
default_border pixel
shadows enable
corner_radius 6
animation_duration_ms 120

# Gaps
gaps inner 3
gaps outer 5
smart_gaps off

blur on
blur_xray on
blur_passes 2
blur_radius 6
for_window [floating] border pixel 2

exec swaybg -o * -i /usr/share/backgrounds/StratOS/zstg/Stratos-Tokyonight-vectorized.png -m fill
for_window [class="Conky"] {
  floating enable;
}
for_window [app_id="wofi"] {
	floating enable;
	move position center;
	resize set 50ppt 50ppt
}
for_window [app_id="dev.faetalize.waytator"] {
  floating enable; resize set 90ppt 90ppt
}
for_window [instance="steam_proton"] {
	floating enable;
}
# Cursor Theming
seat seat0 xcursor_theme Bibata-Modern-Classic 24
# Set colors for client windows
client.focused			 "#060713" "#BAC3FF" "#919DC7" "#BAC3FF"
