# Pywal theme for superfile
# Theme create by: https://github.com/slipstream8125
# Update by(sort by time):
#
# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "onedark"

# ========= Border =========
file_panel_border = "#5C9F9A"
sidebar_border ="#5C9F9A"
footer_border = "#5C9F9A"

# ========= Border Active =========
file_panel_border_active ="#53645E"
sidebar_border_active = "#53645E"
footer_border_active = "#53645E"
modal_border_active = "#53645E"

# ========= Background (bg) =========
full_screen_bg = "#191724"
file_panel_bg = "#191724" 
sidebar_bg = "#191724" 
footer_bg =  "#191724"
modal_bg = "#191724"

# ========= Foreground (fg) =========
full_screen_fg = "#B3B1AD"
file_panel_fg = "#B3B1AD"
sidebar_fg = "#B3B1AD"
footer_fg = "#B3B1AD"
modal_fg = "#B3B1AD"

# ========= Special Color =========
cursor = "#c0c1c0"
correct = "#AAD94C"
error = "#FF3333"
hint = "#36A3D9"
cancel = "#F07178"
# Gradient color can only have two colors!
gradient_color = ["#FFB454", "#36A3D9"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#AAD94C"
file_panel_top_path = "#FFCC66"
file_panel_item_selected_fg = "#36A3D9"
file_panel_item_selected_bg = "#1F2430"

# ========= Sidebar Special Items =========
sidebar_title = "#36A3D9"
sidebar_item_selected_fg = "#36A3D9"
sidebar_item_selected_bg = "#1F2430"
sidebar_divider = "#242936"

# ========= Modal Special Items =========
modal_cancel_fg = "#0F1419"
modal_cancel_bg = "#F07178"

modal_confirm_fg = "#0F1419"
modal_confirm_bg = "#36A3D9"

# ========= Help Menu =========
help_menu_hotkey = "#36A3D9"
help_menu_title = "#F07178"
